(lang dune 2.9)
(cram enable)
(generate_opam_files true)

(maintainers "dedukti-dev@inria.fr")

(package
 (name appaxiom)
 (synopsis "Apply something on Dedukti axioms")
 (depends cmdliner lambdapi))
