(lang dune 2.9)
(name chainprops)
(cram enable)

(generate_opam_files true)
(maintainers "dedukti-dev@inria.fr")

(package
 (name chainprops)
 (synopsis "Make inference steps out of Dedukti propositions")
 (depends
  cmdliner angstrom lambdapi))
