(lang dune 2.9)
(name psnj_qfo)
(cram enable)

(generate_opam_files true)
(maintainers "dedukti-dev@inria.fr")

(package
 (name psnj_qfo)
 (synopsis "Transform PVS-Cert encoded lambdapi to solver friendly encodings")
 (depends cmdliner yojson lambdapi))
