// vim: set syntax=asciidoc textwidth=70 expandtab ts=2 sw=2:
= Translating PVS to Dedukti with Personoj =
Gabriel Hondet <gabriel.hondet@inria.fr>
v1.0, October 2021

_Personoj_ is a suite of tools to translate specifications from
the higher order, highly automated proof assistant
link:http://pvs.csl.sri.com[PVS] to the universal type checker
link:https://deducteam.github.io[Dedukti].

Translating PVS to Dedukti serves mainly two purposes. The first is to
port PVS developments to other proof assistants, so that users of say,
link:https://coq.inria.fr[Coq], could use in their work theorems or
specifications done in PVS. The second is to cross-check PVS
specifications and proofs with an independent checker in order to
increase our trust in these proofs and specifications.

This work is part of a larger project led by the
link:https://deducteam.gitlabpages.inria.fr[Deducteam] made of
link:http://www.lsv.fr/~dowek/Publi/logipedia.pdf[Logipedia] and
link:https://github.com/Deducteam/nubo[Nubo].

== Translating theoretically ==

Translating PVS into Dedukti requires to be able to express a
sufficiently large subset of the theory of PVS into the 
link:http://www.lsv.fr/~dowek/Publi/expressing.pdf[λΠ-calculus modulo
theory]. Such a task is usually not easy. In the case of PVS,
defining the logic of PVS is already tricky, but its core has been
formally studied in
link:https://tel.archives-ouvertes.fr/hal-01673518[F. Gilbert PhD
thesis]. In particular, two languages has been defined. The first
named _PVS-Core_ is the language in which PVS specifications are
written in. It is based on Simple Type Theory with implicit predicate
subtyping, ad-hoc polymorphism and some sort of prenex polymorphism
and dependent types.  In particular, this language does not contain
proof terms and type checking a term is not decidable. The second
language named _PVS-Cert_ is a language for PVS-Core certificates. It
replaces implicit predicate subtyping of PVS-Core with explicit
predicate subtyping. This allows terms to contain proof terms and type
checking terms becomes decidable.

PVS-Cert has been encoded in
link:https://github.com/Deducteam/lambdpi[lambdapi], an extension of
Dedukti with meta-variables. This encoding is described
link:https://hal.inria.fr/hal-03279766[there].
The encoding of PVS-Core is work in progress. In particular, encoding
implicit predicate subtyping requires some procedure to make it
explicit. Personoj provides the encodings that can be used by lambdapi
(in its development version) to explicit PVS-Core specifications and
type check them.

== How to translate and X-check PVS files? ==

We call translation of a PVS file the process of creating a file in
the syntax of lambdapi (suffixed by +.lp+) from a PVS specification
(suffixed by +.pvs+). Cross-checking a PVS file consists in type
checking its translation.

IMPORTANT: this document is focused on the translation of the standard
library of PVS called _Prelude_. Its management is a bit particular
because it is somewhat linked to the lisp code of PVS. Some steps
shouldn't be necessary when translating other libraries such as NASA's
link:https://github.com/nasa/pvslib[pvslib].

TIP: Looking at the scripts used by the continuous integration may
help with the installation and translation.

NOTE: If not stated otherwise, all paths are relative to the root of
the local clone of personoj (if the paths are not absolute). This path
is also assumed to be stored in the environment variable
+$PERSONOJPATH+.

=== Requirements ===

* link:https://github.com/CSL-SRI/PVS[PVS sources] version 7.1
* link:https://github.com/gabrielhdt/lambdapi[lambdapi], branch
  +refiner+
* BSD flavoured +make+
* ksh
* patch

=== Compiling PVS with a patched prelude ===

NOTE: Compiling PVS is required because the prelude must be patched to
remove some sort of _ad-hoc polymorphism_. Because PVS is linked
against the prelude during compilation, we need to patch the prelude
and then compile PVS with the modified prelude.

CAUTION: this tutorial is made for Linux operating systems. PVS
handles poorly BSD systems and I do not use MacOS nor Windows.

[source,sh]
git clone https://github.com/CSL-SRI/PVS
cd PVS
git checkout pvs7.1
export PVSPATH=$(pwd)

The patches to be applied to the prelude are in
+specs/tools/prelude_patches/+ and must be applied in the
order defined by their filename.
[source,sh]
for p in $(find 'tools/specs/prelude_patches/' -name '*.diff' | sort); do
 patch "${PVSPATH}/lib/prelude.pvs" "$p"
done

PVS can then be compiled, the instructions to compile PVS can be found
in +$PVSPATH/INSTALL+.

[NOTE]
--
It's difficult (but possible) to use a system-installed SBCL to
compile PVS. For this, the script +tools/build-pvs.sh+ can be used:
[source,sh]
cp tools/build-pvs.sh "$PVSPATH"/
cd "$PVSPATH"
autoconf
./configure
./build-pvs.sh
--

[TIP]
--
PVS can be loaded into any SBCL session (unless the running SBCL is
not the same as the one PVS has been compiled with) using
[source,lisp]
include::../tools/load-pvs.lisp[]
--

=== Installing lambdapi ===

The easiest way is to use the link:https://opam.ocaml.org[opam]
(version 2.0 or later).

Then we must retrieve the sources of lambdapi on the branch +refiner+,
which can be done in one line:
[source,sh]
git checkout https://github.com/gabrielhdt/lambdapi.git -b refiner

These
link:https://github.com/Deducteam/lambdapi#compilation-from-the-sources[installation
instructions] can then be followed.

[NOTE]
--
A local OPAM switch with all dependencies installed can be set up
using 
[source,sh]
opam switch create .
--
at the root of the local clone of lambdapi

=== Installing personoj ===

The encoding can be install with (BSD) make,
[source,sh]
bmake -C encoding install

The exporter must be loaded by PVS upon startup. 
For this, add the following to +~/.pvs.lisp+

[source,lisp]
include::../tools/load-personoj.lisp[]
(load-personoj)

TIP: +load-personoj+ can be called with a parameter which supersedes
the variable +$PERSONOJPATH+.

=== Translating the Prelude ===

[source,sh]
cd specs/tools/prelude
bmake

will create a set of empty +.lp+ files and translate and type check
other files. The (nearly) empty files stand for theories that can't be
translated yet.

TIP: if the translation fails, ensure that +$PVSPATH+ and
+$PERSONOJPATH+ are correctly set up.

== Implementation details ==

=== Encoding ===

The encoding is a set of lambdapi files in +encoding/+ that define
axioms allowing to type check PVS terms and propositions.

+lhol.lp+ ::
  Simple Type theory expressed as a PTS commonly named λHOL
+pvs_cert.lp+ ::
  Explicit predicate subtyping
+tuple.lp+ ::
  Non dependents tuples. Can also be seen as a non dependent version
  of link:https://doi.org/10.1016/0890-5401(91)90066-B[de Bruijn
  telescopes].
+logical.lp+ ::
  Locical connectives
+eqtup.lp+ ::
  Uncurried equality and disequality, latexmath:[$eq (t, u)$]
+coercions.lp+ ::
  Define coercions to implement implicit predicate subtyping
+extra+ ::
  More definitions and tools
  +arity-tools.lp+ :::
    An encoding of natural numbers used in data structures (they are
    not the natural numbers used in PVS)
+alt+ ::
  Alternate definitions
+examples+ ::
  Some example specification
