# This is a basic workflow to help you get started with Actions

name: check_encoding

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checking out personoj
      uses: actions/checkout@v4

    - name: Use opam
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 4.14.1 # Long term support version

    - name: Install lambdapi
      run: |
        opam pin add 'git+https://github.com/gabrielhdt/lambdapi#coercions'
        opam exec -- why3 config detect

    - name: check encoding
      run: |
        sudo apt-get install --yes --quiet bmake
        opam exec -- bmake encoding
