name: Check markdown links

on: push

jobs:
  markdown-link-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
