name: proof_tools

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: personoj

    - name: setup
      run: ${GITHUB_WORKSPACE}/personoj/tools/bootstrap.sh
      shell: sh

    - name: compile and run tests
      run: |
        cd "${GITHUB_WORKSPACE}"/personoj/proofs/ || exit 1
        (cd dopth || exit 1
         opam switch create . --packages dune --yes
         eval $(opam env)
         bmake tests)
        (cd chainprops || exit 1
         opam switch create . --deps-only --yes
         eval $(opam env)
         opam pin add ~/lambdapi --yes
         eval $(opam env)
         bmake tests)
