name: proof_tools

on: [push]

jobs:
  tools:
    strategy:
      fail-fast: false
      matrix:
        ocaml-compiler:
          - 4.11.1
          # Deactivated to use lambdapi lockfile
          # - 4.11.x
          # - 4.13.x

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use ocaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}

    - name: Pin lambdapi
      run: opam pin add --locked 'git://github.com/gabrielhdt/lambdapi#refiner_why3quant'

    - name: toolbox
      run: |
        cd psnj_toolbox || exit 1
        opam install . --deps-only --yes
        opam install ocamlformat alt-ergo
        opam exec -- why3 config detect
        opam exec -- dune build @fmt
        opam exec -- dune build
        opam exec -- dune test
