name: Translate and typecheck Prelude

on: [push]

jobs:
  translate-typecheck:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - ubuntu-22.04

    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: setup ocaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 4.14.1

    - name: pin lambdapi
      run: opam pin add 'git+https://github.com/gabrielhdt/lambdapi#coercions'

    - name: Install PVS
      run: tools/setup-pvs.sh
      shell: sh

    - name: install personoj
      run: opam exec -- ~/pvs-7.1.0/pvs -raw -L tools/personoj.lisp

    - name: translate and typecheck
      run: |
        PERSONOJPATH="$(realpath .)"
        pushd tests/prelude || exit 1
        PVSPATH=~/pvs-7.1.0
        opam exec -- ${PVSPATH}/pvs -raw -L test.lisp -E '(runall :without-proof-p t :lp-out t :lp-err t)'
        # For archiving
        mkdir /tmp/prelude-lp /tmp/prelude-lpo
        cp *.lpo /tmp/prelude-lpo
        cp *.lp /tmp/prelude-lp

    - name: Archive translations
      uses: actions/upload-artifact@v3
      with:
        name: prelude-lp
        path: /tmp/prelude-lp
        if-no-files-found: error

    - name: Archive signatures
      uses: actions/upload-artifact@v3
      with:
        name: prelude-lpo
        path: /tmp/prelude-lpo
        if-no-files-found: error
