name: pvs_prelude

on: [push]

jobs:
  translate-typecheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: personoj

    - name: setup ocaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 4.11.1

    - name: pin lambdapi
      run: opam pin add 'git://github.com/gabrielhdt/lambdapi#refiner'

    - name: Install PVS
      run: ${GITHUB_WORKSPACE}/personoj/tools/setup-pvs.sh
      shell: sh

    - name: install personoj
      run: |
        opam exec -- bmake -C "${GITHUB_WORKSPACE}"/personoj/encoding install
        cp "${GITHUB_WORKSPACE}/personoj/tools/load-personoj.lisp" ~/.pvs.lisp
        echo '(load-personoj)' >> ~/.pvs.lisp

    - name: translate and typecheck
      run: |
        cd "${GITHUB_WORKSPACE}"/personoj/specs/tools/prelude || exit 1
        # Comment out theories that consume too much memory during 
        # typechecking
        sed -i 's/^floor_ceil$/-floor_ceil/' theories
        sed -i 's/^modulo_arithmetic$/-modulo_arithmetic/' theories
        sed -i 's/^mod$/-mod/' theories
        PERSONOJPATH="${GITHUB_WORKSPACE}"/personoj/
        opam exec -- bmake PERSONOJPATH="${PERSONOJPATH}" PVSPATH=~/PVS
        # For archiving
        mkdir /tmp/prelude-lp /tmp/prelude-lpo
        cp *.lpo /tmp/prelude-lpo
        cp *.lp /tmp/prelude-lp

    - name: Archive translations
      uses: actions/upload-artifact@v2
      with:
        name: prelude-lp
        path: /tmp/prelude-lp
        if-no-files-found: error

    - name: Archive signatures
      uses: actions/upload-artifact@v2
      with:
        name: prelude-lpo
        path: /tmp/prelude-lpo
        if-no-files-found: error
