name: Translator unit tests

on: [push]

jobs:
  translate-typecheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install PVS
      run: tools/setup-pvs.sh
      shell: sh

    - name: Install personoj
      run: ~/pvs-7.1.0/pvs -raw -L tools/personoj.lisp

    - name: translate and compare
      run: |
        cd tests/thy_translation || exit 1
        ~/pvs-7.1.0/pvs -raw -L test.lisp -E '(runall :non-interactive-p t)' -E '(uiop:quit)'

    - name: Archive output
      uses: actions/upload-artifact@v2
      with:
        name: unit-tests-out
        path: tests/thy_translation/*.lp
        if-no-files-found: error
