name: translator

on: [push]

jobs:
  translate-typecheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # We may even use a PVS package (and not recompile it)
    - name: Install PVS
      run: tools/setup-pvs.sh
      shell: sh

    - name: install personoj in PVS
      run: |
        cp "tools/load-personoj.lisp" ~/.pvs.lisp
        echo '(load-personoj)' >> ~/.pvs.lisp

    - name: translate and compare
      run: |
        cd tests/thy_translation || exit 1
        export PVSPATH="${HOME}"/pvs-7.1.0
        export PERSONOJPATH="${GITHUB_WORKSPACE}"
        ${PVSPATH}/pvs -raw -L test.lisp -E '(runall)' -E '(uiop:quit)'
