# This is a basic workflow to help you get started with Actions

name: check_files

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: opam setup
      run: |
        sudo apt install --yes emacs
        sudo wget https://github.com/ocaml/opam/releases/download/2.0.5/opam-2.0.5-x86_64-linux -O /usr/bin/opam
        sudo chmod 755 /usr/bin/opam
        opam init -a --disable-sandboxing --compiler="4.07.1"
        opam update
        opam switch "4.11.1"
        eval $(opam env)
        opam install alt-ergo.2.3.0 --yes
        git clone https://github.com/Deducteam/lambdapi.git lambdapi
        (cd lambdapi || exit 1
         opam pin add -n -k path lambdapi .)
        opam install --deps-only -t -d lambdapi --yes
        (cd lambdapi || exit 1
         make install)
        why3 config --full-config

    - name: check encoding
      run: |
        eval $(opam env)
        lambdapi check encodings/*.lp

    # - name: check paper
    #   run: |
    #     eval $(opam env)
    #     lambdapi check paper/*.lp

    # - name: check prelude
    #   run: |
    #     eval $(opam env)
    #     lambdapi check prelude/*.lp
