# This is a basic workflow to help you get started with Actions

name: check_files

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checking out personoj
      uses: actions/checkout@v2

    - name: recovering cached opam files...
      uses: actions/cache@v2
      with:
        path: ~/.opam
        key: ${{ runner.os }}-ocaml-4.11.1

    - name: setting up opam
      uses: avsm/setup-ocaml@v1
      with:
        ocaml-version: 4.11.1

    # Runs a set of commands using the runners shell
    - name: install lambdapi
      run: |
        opam pin add alt-ergo 2.3.1
        git clone https://github.com/Deducteam/lambdapi.git lambdapi
        (cd lambdapi || exit 1
         git checkout 3e5c7ee2388d233fdca05776009b5cb158e48d97
         opam pin add lambdapi .)
        opam install lambdapi
        eval $(opam env)
        why3 config --full-config

    - name: check encoding
      run: |
        eval $(opam env)
        lambdapi check encodings/*.lp

    - name: check paper
      run: |
        eval $(opam env)
        lambdapi check paper/*.lp

    # - name: check prelude
    #   run: |
    #     eval $(opam env)
    #     lambdapi check prelude/*.lp
